### ISSUE TITLE
Bug: Error happened when flag containing space

### ISSUE THREAD

**Issue by imcuttle** [mklabs/gentle-cli#2]
- Actual
```
cli()
  .use('node -e " console.log(\'foo\') "')
  .end((err, { text }) => console.log(text))
```

Throw following error:
```
    [eval]:1
    "
    ^
    
    SyntaxError: Invalid or unexpected token
```

- Expected
```javascript
cli()
  .use('node -e " console.log(\'foo\') "')
  .end((err, { text }) => console.log(text))

// log: foo
```

**Comment by mklabs** [comment]
Does it raise the same error without a space ? Or is it with `node -e` ?

**Comment by imcuttle** [comment]
It works well without space and quote 
[repl here](https://runkit.com/moyuyc/gentle-cli-space-bug)

**Comment by mklabs** [comment]
Thanks! I'll try to work on it this afternoon.

**Comment by mklabs** [comment]
After further investigating, it is due to quotes, not spaces. Still thinking about if it something that needs to be fixed.

**Comment by mklabs** [comment]
Okay, there's definitely room for improvements. Don't consider my previous comment ;) Switching to simpler `exec` instead of `spawn` seems to fix it, as well as #1

**Comment by mklabs** [comment]
@imcuttle fixed, let me know if you have another issue with it or reopen, same for #1

**Comment by imcuttle** [comment]
Wow, It's extremely fast. Thanks!

And when is it released?

**Comment by mklabs** [comment]
Well ... now ;) I just forgot to publish to npm.
